version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      root-production-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      root-development-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/cli"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      cli-production-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      cli-development-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/gitbook"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    groups:
      gitbook-dependencies:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
