/**
 * Auth barrel — re-exports every public symbol so existing
 * `import { … } from "../services/auth.js"` lines keep working.
 *
 * Actual implementations live in:
 *   - ./provider-credentials.js  (getProviderCredentials, markAccountUnavailable, clearAccountError)
 *   - ./api-key-validation.js    (extractApiKey, requireValidApiKey, enforceApiKeyPolicy, …)
 *   - ./api-key-helpers.js       (buildApiKeyUsageSummaryResponse, UI helpers, getters, …)
 */

// ── Provider credential management ──────────────────────────────────
export {
  getProviderCredentials,
  markAccountUnavailable,
  clearAccountError,
} from "./provider-credentials.js";

// ── API key validation & enforcement ────────────────────────────────
export {
  extractApiKey,
  requireValidApiKey,
  isValidApiKey,
  apiKeyErrorResponse,
  enforceApiKeyPolicy,
  logApiKeyPresence,
  normalizeApiKeyFailureLog,
  getLimitStatusForUi,
  getApiKeyLimitSnapshot,
  attachApiKeyContext,
  applyApiKeyContextToUsage,
  buildApiKeyDebugMeta,
  getApiKeyLimitCode,
  getApiKeyLimitState,
  getApiKeyInfo,
  getApiKeyValue,
  isApiKeyRequired,
  canSkipApiKeyValidation,
  getApiKeyFailureStatus,
  getApiKeyFailureMessage,
  getApiKeyFailurePayload,
  buildApiKeyError,
  authFailureToErrorResponse,
  getRequestApiKeyContext,
} from "./api-key-validation.js";

// ── API key helpers, builders, formatters ───────────────────────────
export {
  buildApiKeyUsageSummaryResponse,
  isLimitExceeded,
  getApiKeyMetricLabel,
  getApiKeyPeriodLabel,
  formatApiKeyLimitMessage,
  getApiKeyLimitRemainingText,
  getApiKeyNextResetText,
  buildApiKeyLimitUiState,
  getValidatedApiKey,
  getValidatedApiKeyId,
  getValidatedApiKeyName,
  getValidatedApiKeyLimit,
  hasApiKeyLimit,
  buildApiKeyRequestMeta,
  getApiKeyValidationSummary,
  getApiKeyLimitResponseMeta,
  getApiKeyLimitDisplay,
  isApiKeyPresent,
  getApiKeyAuthMode,
  getApiKeyLimitKind,
  getApiKeyLimitWindow,
  getApiKeyLimitValue,
  getApiKeyCurrentValue,
  getApiKeyRemainingValue,
  getApiKeyResetAt,
  buildApiKeyHeaderDebug,
  buildApiKeyLimitStatus,
  getRequestApiKeyValue,
  getRequestApiKeyValidationState,
  getApiKeyPolicySnapshot,
  getApiKeyLimitSummary,
  buildApiKeyValidationResult,
  getApiKeyEnforcementContext,
  applyApiKeyEnforcementLog,
  getApiKeyRequestTelemetry,
  getApiKeyRequestGuardResult,
  buildMissingApiKeyResponse,
  buildInvalidApiKeyResponse,
  buildInactiveApiKeyResponse,
  buildExceededApiKeyResponse,
  hasExceededApiKeyLimit,
  getApiKeyAuthDetails,
  getApiKeySummaryForLog,
  getApiKeyAuthSnapshot,
  getApiKeyLimitTelemetry,
  getApiKeyLimitResponse,
  getApiKeyRateLimitHint,
  buildApiKeyStatusBadge,
  getApiKeyLimitReason,
  getApiKeyLimitMessage,
  buildApiKeyGuardContext,
  buildApiKeyUsageContext,
  hasApiKeyGuardError,
  getApiKeyGuardErrorResponse,
  getApiKeyGuardErrorPayload,
  buildApiKeyResult,
  getApiKeyLimitUiStatus,
  getApiKeyLimitUiMessage,
  getApiKeyLimitUiRemaining,
  getApiKeyLimitUiReset,
  getAuthRequestApiKey,
  getAuthValidationInfo,
  getApiKeyErrorLimitMeta,
  getApiKeyErrorCode,
  buildApiKeyDebugContext,
  getApiKeyGuardMeta,
  buildApiKeyLimitDetails,
  getApiKeyRemainingText,
  getApiKeyStatusText,
  getApiKeyResetText,
  getRequestApiKeyId,
  getRequestApiKeyName,
  getRequestApiKeyLimitState,
  getRequestApiKeyStatus,
  getRequestApiKeyTelemetry,
  getRequestApiKeyUi,
  getRequestApiKeySummary,
  getApiKeyQuotaState,
  getApiKeyQuotaExceeded,
  getApiKeyQuotaMeta,
} from "./api-key-helpers.js";
